language: python
python:
  - "2.7"
  - "3.4"
# commands to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgdal1-dev
  - gdal-config --version
  - pip install --upgrade pip
# command to install pygdal
install:
  - pip install -v -e ./$(gdal-config --version)
# command to run tests
script: python -c "from osgeo import gdal, ogr, osr"
